### PR TITLE
update dependencies, remove level devDependency

### PR DESCRIPTION
**Pull request by ralphtheninja**
Preparing for `packager@1.0.0`

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@juliangruber I removed the devDependency for `level` and replaced with `leveldown` instead. It feels a bit odd to have it as any form of dependency since `level` depends on this module`.

**Comment by ralphtheninja** [comment]
I have too many PRs hanging so you have to excuse me if I go ahead and merge the trivial ones ;)

**Comment by ralphtheninja** [comment]
```
$ npm publish --tag=next
+ level-packager@1.0.0-0
```

**Comment by ralphtheninja** [comment]
Publishing a `next` version on this module so I can test it out with both `level` and `level-hyper`.

**Comment by juliangruber** [comment]
+1 :)

**Pull request merged**
