### PR TITLE
Restore node 4

### PR DESCRIPTION
**Pull request by vweevers**

### CODE REVIEW

**Comment by vweevers** [comment]
Closes #38.

**Comment by vweevers** [comment]
Triggered a rebuild of the node 4 job, now passing.

**Comment by vweevers** [comment]
@ralphtheninja can you add me to npm?

**Comment by vweevers** [comment]
(and to `level` as well) (thanks!)

**Comment by vweevers** [comment]
Or @juliangruber :)

**Comment by juliangruber** [comment]
added you to both

**Comment by vweevers** [comment]
2.0.2

**Pull request merged**
